server:
  port: 9903

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
#      defaultZone: http://@eureka.user.name@:@eureka.user.password@@localhost:9900/eureka/
      defaultZone: http://localhost:9900/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: wx-recycle #payment_routh    #路由的ID，唯一路由表示，没有实际作用不重复就好
          #uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://wx-web   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名
          predicates:
            - Path=/wx/recycle/**          #断言，路径相匹配的进行路由



