server:
  port: 9902

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
#      defaultZone: http://@eureka.user.name@:@eureka.user.password@@localhost:9900/eureka/
      defaultZone: http://localhost:9900/eureka/

spring:
  application:
    name: wx-web-server
  cloud:
    loadbalancer:
      retry:
        enabled: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.10.101:3306/recruit_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: sa